name = "cactus-auth"
main = "src/index.js"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "cactus-auth-db"
database_id = "de5388b3-9e47-4141-afb2-f28ac6748bcb"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "5a0a8a06f7924a93ba2d378cb093e4e3"

[vars]
AUTH_DOMAIN = "auth.cactus.watch"
COOKIE_DOMAIN = ".cactus.watch"
SESSION_TTL_DAYS = "30"
ENVIRONMENT = "production"
