name = "cactus-watch-central"
main = "src/index.js"
compatibility_date = "2024-12-01"

# Cron trigger — scrape daily at 6 AM AZ time (1 PM UTC)
[triggers]
crons = ["0 13 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "cactus-watch-db"
database_id = "b4e43bc9-fd98-437e-b216-30df9afb4f0e"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "cbbdc642de8749a7b3a1a44c6890c8c6"

[limits]
subrequests = 50000

[vars]
ENVIRONMENT = "production"
